# Generated by Django 3.0.1 on 2020-04-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(default='', max_length=50)),
                ('passwd', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('salary', models.CharField(default='', max_length=15)),
                ('mob', models.CharField(default='', max_length=15)),
                ('address', models.CharField(default='', max_length=200)),
                ('post', models.CharField(default='', max_length=200)),
                ('dob', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollid', models.CharField(default='', max_length=50)),
                ('passwd', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('branch', models.CharField(default='', max_length=50)),
                ('year', models.CharField(default='', max_length=50)),
                ('cgpa', models.CharField(default='', max_length=15)),
                ('mob', models.CharField(default='', max_length=15)),
                ('address', models.CharField(default='', max_length=200)),
                ('dob', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
